
#ifndef _PDB_Residue_AtomLibrary_H_
#define _PDB_Residue_AtomLibrary_H_

#include "pdb/residue/name.h"

namespace mysimulator {

  static const unsigned int
  AtomStart4Residue[NumberResidueNames] = {
    0,
    10,
    34
  };

  static const unsigned int ResidueSize[NumberResidueNames] = {
    10,
    24,
    7
  };

}

#include "pdb/atom/name.h"

namespace mysimulator {

  static const PDBAtomName Atoms4Residue[] = {
    AtomCA,       // Start Ala
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomH,
    AtomHA,
    AtomHB1,
    AtomHB2,
    AtomHB3,      // End Ala
    AtomCA,       // Start Arg
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG,
    AtomCD,
    AtomNE,
    AtomCZ,
    AtomNH1,
    AtomNH2,
    AtomH,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHG2,
    AtomHG3,
    AtomHD2,
    AtomHD3,
    AtomHE,
    AtomHH11,
    AtomHH12,
    AtomHH21,
    AtomHH22,     // End Arg
    AtomCA,       // Start Asn
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG,
    AtomOD1,
    AtomND2,
    AtomH,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHD21,
    AtomHD22,     // End Asn
    AtomCA,       // Start Asp
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG,
    AtomOD1,
    AtomOD2,
    AtomH,
    AtomHA,
    AtomHB2,
    AtomHB3,      // End Asp
    AtomCA,       // Start Cys
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomSG,
    AtomH,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHG,       // End Cys
    AtomCA,       // Start Gln,
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG,
    AtomCD,
    AtomOE1,
    AtomNE2,
    AtomH,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHG2,
    AtomHG3,
    AtomHE21,
    AtomHE22,     // End Gln
    AtomCA,       // Start Glu
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG,
    AtomCD,
    AtomOE1,
    AtomOE2,
    AtomH,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHG2,
    AtomHG3,      //End Glu,
    AtomCA,       // Start Gly
    AtomN,
    AtomC,
    AtomO,
    AtomH,
    AtomHA2,
    AtomHA3,      // End Gly
    AtomCA,       // Start His
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG,
    AtomND1,
    AtomND2,
    AtomCE1,
    AtomNE2,
    AtomH,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHD1,
    AtomHD2,
    AtomHE1,
    AtomHE2,      // End His
    AtomCA,       // Start ILE
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG1,
    AtomCG2,
    AtomCD1,
    AtomH,
    AtomHA,
    AtomHB,
    AtomHG12,
    AtomHG13,
    AtomHG21,
    AtomHG22,
    AtomHG23,
    AtomHD11,
    AtomHD12,
    AtomHD13,     // End ILE
    AtomCA,       // Start LEU
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG,
    AtomCD1,
    AtomCD2,
    AtomH,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHG,
    AtomHD11,
    AtomHD12,
    AtomHD13,
    AtomHD21,
    AtomHD22,
    AtomHD23,     // End Leu
    AtomCA,       // Start Lys
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG,
    AtomCD,
    AtomCE,
    AtomNZ,
    AtomH,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHG2,
    AtomHG3,
    AtomHD2,
    AtomHD3,
    AtomHE2,
    AtomHE3,
    AtomHZ1,
    AtomHZ2,
    AtomHZ3,      // End Lys
    AtomCA,       // Start Met
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG,
    AtomSD,
    AtomCE,
    AtomH,
    AtomH1,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHG2,
    AtomHG3,
    AtomHE1,
    AtomHE2,
    AtomHE3,      // End Met
    AtomCA,       // Start Phe,
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG,
    AtomCD1,
    AtomCD2,
    AtomCE1,
    AtomCE2,
    AtomCZ,
    AtomH,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHD1,
    AtomHD2,
    AtomHE1,
    AtomHE2,
    AtomHZ,       // End Phe
    AtomCA,       // Start Pro
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG,
    AtomCD,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHG2,
    AtomHG3,
    AtomHD2,
    AtomHD3,      // End Pro
    AtomCA,       // Start Ser
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomOG,
    AtomH,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHG,       // End Ser
    AtomCA,       // Start Thr
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomOG1,
    AtomCG2,
    AtomH,
    AtomHA,
    AtomHB,
    AtomHG1,
    AtomHG21,
    AtomHG22,
    AtomHG23,     // End Thr
    AtomCA,       // Start Trp
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG,
    AtomCD1,
    AtomCD2,
    AtomNE1,
    AtomCE2,
    AtomCZ2,
    AtomCZ3,
    AtomCH2,
    AtomH,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHD1,
    AtomHE1,
    AtomHE3,
    AtomHZ2,
    AtomHZ3,
    AtomHH2,        // End Trp
    AtomCA,         // Start Tyr
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG,
    AtomCD1,
    AtomCD2,
    AtomCE1,
    AtomCE2,
    AtomCZ,
    AtomOH,
    AtomH,
    AtomHA,
    AtomHB2,
    AtomHB3,
    AtomHD1,
    AtomHD2,
    AtomHE1,
    AtomHE2,
    AtomHH,         // End Tyr
    AtomCA,         // Start Val
    AtomN,
    AtomC,
    AtomO,
    AtomCB,
    AtomCG1,
    AtomCG2,
    AtomH,
    AtomHA,
    AtomHB,
    AtomHG11,
    AtomHG12,
    AtomHG13,
    AtomHG21,
    AtomHG22,
    AtomHG23        // End Val
  };

}

#endif

